from relex.modules.seq2vec_encoders.bag_of_embeddings_encoder import BagOfEmbeddings
from relex.modules.seq2vec_encoders.seq2seq_pool_encoder import Seq2SeqPoolEncoder
from relex.modules.seq2vec_encoders.gcn import GCN
